### ISSUE TITLE
`help commands` is less readable now

### ISSUE THREAD

**Issue by jonathandturner** [nushell/wasm-nu#7]
We may want to play with the size of columns a bit. Just did `help commands` and got this (notice the command name is hard to read):

![Screenshot from 2020-07-15 21-02-52](https://user-images.githubusercontent.com/547158/87526289-c8ac5d00-c6de-11ea-9457-b6f8c580a58a.png)

**Comment by jzaefferer** [comment]
Good point. I'll take a look at that (later).

This got me thinking, to run "help commands" once on startup and use that list for some kind of autocomplete or suggestions. Or for testing the output of various commands in this context
